namespace _08_Try_Catch
{
    internal class Program
    {
        static void Main(string[] args)
        {
            //TRY_CATCH: Fırlatılan Exception'ları yakalarak program akışını durdurmadan hata durumunda ne yapılması gerektiğini tanımlar.




            //try
            //{
            //    Console.WriteLine("Bir sayı giriniz");
            //    int sayi = Convert.ToInt32(Console.ReadLine());
            //    Console.WriteLine(sayi / 0);
            //}
            //catch (FormatException)
            //{
            //    Console.WriteLine("Sayı rakamlardan oluşur!!!");
            //}
            //catch (DivideByZeroException)
            //{
            //    Console.WriteLine("Sayı 0 a bölünemez!!!");
            //}
            //catch (Exception)
            //{
            //    Console.WriteLine("Bilinmeyen Hata!!!");
            //}


            //try
            //{
            //    Console.WriteLine("Bir sayı giriniz");
            //    int sayi = Convert.ToInt32(Console.ReadLine());
            //    Console.WriteLine(sayi / 0);
            //}
            //catch (Exception e)
            //{
            //    Console.WriteLine(e);
            //    Console.WriteLine(e.Message);
            //}


            #region Kullanıcıdan iki sayı alınacak ve toplamı yazdırılacak.
            // iki sayıdan biri hatalı girilirse o sayı tekrar istenilecek.
            #endregion
        }
    }
}
